name: "Pull Request Labeler"
run-name: ${{ github.actor }} created pull request labeler

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  triage:
    if: >-
      github.event.pull_request.user.login != 'octobot' &&
      github.event.pull_request.user.login != 'dependabot[bot]'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        configuration-path: .github/pr-labeler-config.yaml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
